### ISSUE TITLE
Colour scheme

### ISSUE THREAD

**Issue by charliearlie** [charliearlie/to-be-named#18]
These can be stores as SASS variables.

My favourite..
1.
![image](https://user-images.githubusercontent.com/7570492/46654047-aac3d700-cb9f-11e8-8be4-c15eea75c7cc.png)

Other palettes
2.
![image](https://user-images.githubusercontent.com/7570492/46654177-10b05e80-cba0-11e8-9f1c-55e40f483ced.png)

3.
![image](https://user-images.githubusercontent.com/7570492/46654301-6d137e00-cba0-11e8-8168-7c049914f6f2.png)

If you pick a number that isn't one, we'll decide afterwards.

**Comment by LorenzoKoundouris** [comment]
1 looks nice

**Comment by charliearlie** [comment]
I'm glad we have similar taste, although I would like a yellow. I'm so indecisive.
